baseURL = 'https://gh.tamanegi.tech/gh-test'
languageCode = 'ja'
defaultContentLanguage = 'ja'
title = 'テストサイト|タイトル '
theme = 'hugo-book'
enableGitInfo = true
[params]
  BookRepo = 'https://gh.tamanegi.tech/gh-test'
  BookCommitPath = 'commit'
  BookServiceWorker = true         
